use c++1y flag on Linux
We use c++14 features so we better enable the flag. Fixes compilation
bugs like:
./wayward/support/data_franca/adapter.hpp:61:5: error: 'auto' return
without trailing returntype; deduced return types are a C++14 extension
	auto make_adapter(T&& object, Bitflags<Options> options) {
	^